version: '3.4'

services:
  aqalnet.api:
    image: ${DOCKER_REGISTRY-}aqalnetapi
    container_name: Aqalnet.Api
    build:
      context: .
      dockerfile: src/Aqalnet.Api/Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - aqalnet.db

  aqalnet.db:
    image: postgres:latest
    container_name: Aqalnet.Db
    ports:
       - 5432:5432
    environment:
       - POSTGRES_DB=AqalnetDb
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  aqalnet.redis:
    image: redis:latest
    container_name: Aqalnet.Redis
    restart: always
    ports:
      - 6379:6379

volumes:
  db-data:
    driver: local

