version: '3.4'

services:
  aqalnet.api:
    image: ${DOCKER_REGISTRY-}aqalnetapi
    container_name: Aqalnet.Api
    build:
      context: .
      dockerfile: src/Aqalnet.Api/Dockerfile
    depends_on:
      - aqalnet.db

  aqalnet.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Aqalnet.Db
    ports:
       - 8001:1433
    environment:
       - ACCEPT_EULA=Y
       - SA_PASSWORD=Admin@123
    volumes:
      - db-data:/var/opt/mssql

  aqalnet.redis:
    image: redis:latest
    container_name: Aqalnet.Redis
    restart: always
    ports:
      - 6379:6379

volumes:
  db-data:
    driver: local

